### PR TITLE
[G2M] journals/fix - remove optional chaining

### PR DESCRIPTION
**Pull request by hyx131**

### CODE REVIEW

**Review by woozyking — APPROVED** [review]
version problem?

**Comment by hyx131** [comment]
> version problem?

ya, not sure if we could upgrade to node 14 for avail-bot

**Comment by woozyking** [comment]
> > version problem?
> 
> ya, not sure if we could upgrade to node 14 for avail-bot

yes we can. the only problem with node 14 is with firstorder, something to do with either express or lambda. avail-bot should be fine

**Review by woozyking — APPROVED** [review]

**Comment by hyx131** [comment]
> > > version problem?
> > 
> > 
> > ya, not sure if we could upgrade to node 14 for avail-bot
> 
> yes we can. the only problem with node 14 is with firstorder, something to do with either express or lambda. avail-bot should be fine

okies, gonna proceed with upgrading to 14

**Pull request merged**
